apiVersion: apps/v1
kind: Deployment
metadata:
  name: etrain-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etrain-frontend
  template:
    metadata:
      labels:
        app: etrain-frontend
    spec:
      containers:
        - name: etrain-frontend
          image: etrain-frontend:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: etrain-frontend
spec:
  type: NodePort
  selector:
    app: etrain-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080