apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-service
  template:
    metadata:
      labels:
        app: train-service
    spec:
      containers:
        - name: train-service
          image: train-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5441/train
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: Admin@123
            - name: TOKEN_VALIDATION_URL
              value: http://etrain.local
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
spec:
  selector:
    app: train-service
  ports:
    - port: 8082